### ISSUE TITLE
Actualizar horarios

### ISSUE THREAD

**Issue by advy99** [DEIIT/Ingenieria-Informatica#12]
Se ha decidido quitar los horarios y en su lugar poner un enlace a la página web de la ETSIIT donde estan disponibles

**Comment by advy99** [comment]
Solved in ee52d6dee359f06744c643461d463a3095e91c34

He venido a arreglarlo, y resulta que @Groctel ya lo habia hecho.

**Comment by Groctel** [comment]
@advy99 Te quiero @advy99
